version: "3.8"
services:
  crypto-finch:
    image: julfinch/crypto-finch:v1
    build: .
    container_name: crypto-finch_c
    ports:
      - '3000:3000'
    volumes:
      - ./src:/app/src
    env_file:
      - ./.env
    stdin_open: true
    tty: true